import React from "react";
import { liveStatus, readLabJson } from "./liveStatus";
import { HOSTED, HOSTED_MODEL } from "./HostedSession.jsx";

const DOMAINS = {
  water: { name:"Water", subtitle:"Treatment & distribution", color:"#65dbcf", route:"hmi", incident:"storm_supply", incidentName:"Severe storm", scenario:"normal_day", chain:["Intake","Treatment","Storage","City"], tags:["distribution_flow_m3h","clearwell_level_pct","chlorine_residual_mg_l"], labels:["Delivered flow","Clearwell","Chlorine residual"], units:["m³/h","%","mg/L"], note:"Follow the water from intake to customers. The PLC reacts to sensor measurements; auxiliary equipment has separate commands and field feedback." },
  nuclear: { name:"Nuclear", subtitle:"Generic PWR & secondary cycle", color:"#c0a4f4", route:"nuclear", incident:"regional_grid_disturbance", incidentName:"Regional electrical disturbance", scenario:"normal_operation", chain:["Reactor","Steam","Turbine","Supply"], tags:["reactor_power_pct","electric_output_mwe","condenser_pressure_kpa_abs"], labels:["Reactor power","Station output","Condenser pressure"], units:["%","MWe","kPa"], note:"The reactor and secondary cycle are separated. The agent can suggest only secondary-side targets; independent protection retains shutdown authority." },
  grid: { name:"Power grid", subtitle:"Generation, networks & demand", color:"#efc47d", route:"grid", incident:"regional_supply_shortfall", incidentName:"Regional supply shortage", scenario:"normal_dispatch", chain:["Sources","Network","Substations","City"], tags:["total_generation_mw","frequency_model_hz","unserved_load_mw"], labels:["Generation","Frequency","Unserved load"], units:["MW","Hz","MW"], note:"The network balances generation and customer demand. Connected components are solved separately, so a service shortfall has an observable location and duration." },
};
const CHAPTERS=[
  { title:"Meet the system",time:"1 min",heading:"Can local AI help operate critical infrastructure?",copy:"Three simulated systems. One research question: can an agent improve supervisory decisions while staying inside a boundary we can inspect?",say:"Start with the research question. This is an isolated teaching lab with simplified dynamics, not a connection to a real utility. We will observe a process, introduce a disturbance and inspect the agent's decision." },
  { title:"Establish a baseline",time:"2 min",heading:"The process already has a controller.",copy:"Deterministic logic runs the equipment. Establish a short baseline before introducing either a disturbance or an AI proposal.",say:"AI is not the primary controller. Sensors feed deterministic control loops and independent protections. A useful experiment starts with a recorded operating state and an explicit control mode." },
  { title:"Introduce a disturbance",time:"2 min",heading:"Make the consequences observable.",copy:"Run a predefined external incident, then pause after ten simulated minutes. Compare service availability, sensor values and alarms with the captured baseline.",say:"Watch how the equipment responds and how much service remains available. These incident severities and service areas are fictional. A nuclear trip is not an estimate of offsite harm." },
  { title:"Inspect the AI decision",time:"3 min",heading:"A proposal must earn permission.",copy:"The model receives the captured operating state. Its proposal passes through the same deterministic gate on a detached copy, with no control changes applied.",say:"Separate three things: what the model says, what it proposes and what the gate permits. A rejection can demonstrate that a boundary worked. Model-emitted reasoning is evidence to question, not proof of the model's intent." },
  { title:"Examine the evidence",time:"2 min",heading:"Measure behavior. Keep the claims bounded.",copy:"Compare the recorded observations and run a paired study. Identical physical inputs let us probe whether irrelevant context changes a proposal.",say:"A service deficit is a measured simulation outcome; a gate rejection is an enforced boundary. A two-case label test is a pilot observation. We need repeated controlled experiments before claiming optimization, alignment or absence of bias." },
];
async function api(path,body,signal){
  const response=await fetch(`/api/v1${path}`,{method:body===undefined?"GET":"POST",headers:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body),signal});
  return readLabJson(response);
}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const reading=(plant,tag)=>Number.isFinite(plant?.sensors?.[tag]?.value)?plant.sensors[tag].value.toFixed(1):"—";
const compact=(plant)=>({minute:plant.elapsed_minutes,mode:plant.controller_mode,sensors:plant.sensors,impact:plant.operations?.impact,alarms:plant.active_alarms||plant.alarms||[]});

export default function Walkthrough({ domain,setDomain,chapter,setChapter,evidence,setEvidence,water,infrastructure,onOpen,onWaterAction,onInfrastructureCommand }){
  const [notes,setNotes]=React.useState(false),[large,setLarge]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState("");
  const [connection,setConnection]=React.useState("checking"),[connectionError,setConnectionError]=React.useState("");
  const [agent,setAgent]=React.useState(null),[records,setRecords]=React.useState([]),[job,setJob]=React.useState(null),[decision,setDecision]=React.useState(null),[thinking,setThinking]=React.useState(false);
  const [session,setSession]=React.useState(null),[cooldown,setCooldown]=React.useState(0);
  const info=DOMAINS[domain],part=CHAPTERS[chapter],plant=domain==="water"?water:infrastructure[domain],saved=evidence[domain]||{};
  React.useEffect(()=>{const controller=new AbortController();let timer;async function poll(){try{const [s,r]=await Promise.all([api("/agents/state",undefined,controller.signal),api(`/agents/records?domain=${domain}`,undefined,controller.signal)]);if(!controller.signal.aborted){setAgent(s);setRecords(r);setConnection("online");setConnectionError("");}if(job){const j=s.jobs.find(x=>x.id===job);if(j?.status==="complete"){const d=await api(`/agents/records/${j.record_id}`,undefined,controller.signal);if(!controller.signal.aborted){setDecision(d);setJob(null);}}else if(j?.status==="failed"){setError(j.error);setJob(null);}}}catch(e){if(!controller.signal.aborted){setConnection("offline");setConnectionError(e.message);}}if(!controller.signal.aborted)timer=setTimeout(poll,6000);}poll();return()=>{controller.abort();clearTimeout(timer);};},[domain,job]);
  // Hosted sessions are metered. Show the remaining allowance rather than letting a
  // visitor discover the limit by hitting it.
  React.useEffect(()=>{
    if(!HOSTED) return undefined;
    let stopped=false;
    const read=()=>fetch("/api/session").then(r=>r.json()).then(d=>{if(!stopped)setSession(d);}).catch(()=>{});
    read();const timer=setInterval(read,15000);
    return()=>{stopped=true;clearInterval(timer);};
  },[]);
  React.useEffect(()=>{
    if(cooldown<=0) return undefined;
    const timer=setTimeout(()=>setCooldown(cooldown-1),1000);
    return()=>clearTimeout(timer);
  },[cooldown]);
  const pending=busy||agent?.jobs.some(j=>j.status==="running");
  const ready=connection==="online"&&agent?.model.available&&agent?.model.model_pulled;
  const status=liveStatus({connection,agent,plant,records,hosted:import.meta.env.VITE_HOSTED==='true'});
  const perform=async(fn)=>{setBusy(true);setError("");try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const state=async()=>domain==="water"?(await api("/state")).plant:(await api("/infrastructure/state"))[domain];
  const command=async(action,options={})=>{if(domain!=="water")return onInfrastructureCommand(domain,action,options);const current=await api("/state");if(!current.active_run_id)throw new Error("Prepare a water baseline first.");return api(`/runs/${current.active_run_id}/${action}`,action==="step"?options:{});};
  const prepare=()=>perform(async()=>{
    const previous=await api(`/training/${domain}/export`);download(`${domain}-before-demo-${previous.run_id}.json`,previous);
    if(domain==="water"){const run=await api("/runs",{scenario:info.scenario,controller_mode:"baseline",speed:1,seed:42});await api(`/runs/${run.id}/reset`,{});}
    else await command("reset",{scenario:info.scenario,controller_mode:"baseline",speed:1});
    await command("step",{minutes:5});
    const [baseline,report]=await Promise.all([state(),api(`/training/${domain}`)]);
    setEvidence(old=>({...old,[domain]:{baseline:compact(baseline),runId:report.run_id}}));setDecision(null);
  });
  const incident=()=>perform(async()=>{
    const report=await api(`/training/${domain}`);if(report.run_id!==saved.runId)throw new Error("This exercise changed. Capture a fresh baseline before the demonstration.");
    await command("pause");
    await api(`/operations/${domain}`,{action:"incident",incident_id:info.incident,duration_minutes:45,start_running:false});
    await command("step",{minutes:10});
    const after=await state();setEvidence(old=>({...old,[domain]:{...old[domain],after:compact(after)}}));
  });
  const infer=(study=false)=>perform(async()=>{const j=await api(`/agents/${domain}/${study?"study":"cycle"}`,study?{kind:"label_invariance",thinking}:{thinking,evaluate_only:true});if(HOSTED)setCooldown(10);setJob(j.id);setDecision(null);});
  const openEvidence=()=>onOpen("agents",domain,decision?.id || (chapter===4?latestStudy?.id:validRecords[0]?.id));
  const latestStudy=records.find(r=>r.record_type==="study"&&r.status==="study_complete");
  const validRecords=records.filter(r=>r.status==="complete"&&r.evaluate_only===true);
  const selected=decision?.record_type!=="study"?decision:null;
  const choose=(d)=>{setDomain(d);setDecision(null);setError("");};
  return <main className={`page walkthrough ${large?"walk-large":""}`} style={{"--domain-color":info.color}}>
    <div className="walk-topline"><span className="eyebrow">Critical infrastructure · {import.meta.env.VITE_HOSTED==='true'?'cloud AI sandbox':'local AI research'}</span><div><button aria-pressed={notes} onClick={()=>setNotes(!notes)}>{notes?"Hide":"Show"} presenter notes</button><button aria-pressed={large} onClick={()=>setLarge(!large)}>{large?"Standard":"Presentation"} view</button></div></div>
    <div className="walk-hero"><div><span className="walk-chapter">{String(chapter+1).padStart(2,"0")} / 05 · {part.time}</span><h1>{part.heading}</h1><p>{part.copy}</p></div><div className="walk-readiness"><span className={`walk-live-dot ${ready?"ready":""}`} /><strong>{status.model}</strong><small>{agent?.model.model||(HOSTED?HOSTED_MODEL:"—")} · {status.records}</small>{HOSTED&&session?.active&&<span className="walk-allowance">{session.ai_remaining} of 10 AI calls · {Math.max(0,Math.round((session.expires-Date.now())/60000))} min left</span>}<span className="walk-authority">{status.plant}</span></div></div>
    <nav className="walk-chapters" aria-label="Demonstration chapters">{CHAPTERS.map((c,i)=><button key={c.title} aria-current={chapter===i?"step":undefined} className={chapter===i?"active":""} onClick={()=>setChapter(i)}><span>{i+1}</span><strong>{c.title}</strong><small>{c.time}</small></button>)}</nav>
    {notes&&<aside className="walk-notes"><span>PRESENTER NOTES · ABOUT 10 MINUTES TOTAL</span><p>{part.say}</p></aside>}
    {(error||connectionError)&&<div className="training-error" role="alert">{error||connectionError}<button onClick={()=>{setError("");setConnectionError("");}}>Dismiss</button></div>}
    <section className="walk-domains" aria-label="Select a simulation">{Object.entries(DOMAINS).map(([d,item])=><button key={d} disabled={pending} className={domain===d?"selected":""} aria-pressed={domain===d} onClick={()=>choose(d)} style={{"--card-color":item.color}}><span className="walk-domain-icon" aria-hidden="true">{d==="water"?"◉":d==="nuclear"?"⚛":"ϟ"}</span><span><strong>{item.name}</strong><small>{item.subtitle}</small></span><b>{d==="water"?"09":"08"}<small>auxiliary assets</small></b></button>)}</section>
    {chapter===0&&<section className="walk-system"><div><span className="eyebrow">Follow the process</span><h2>{info.name} simulation</h2><p>{info.note}</p><button className="walk-primary" onClick={()=>onOpen(info.route,domain)}>Explore {info.name.toLowerCase()} control room →</button></div><div className="walk-flow">{info.chain.map((label,i)=><React.Fragment key={label}><div><span>0{i+1}</span><strong>{label}</strong><i aria-hidden="true" /></div>{i<3&&<b aria-hidden="true">→</b>}</React.Fragment>)}</div><div className="walk-boundary"><span>Sensor observations</span><b>→</b><span>Bounded AI proposal</span><b>→</b><strong>Required gate</strong><b>→</b><span>PLC supervisory targets</span></div></section>}
    {(chapter===1||chapter===2)&&<section className="walk-experiment"><div className="walk-action"><span className="eyebrow">{chapter===1?"01 · Capture reference state":"02 · Observe resilience"}</span><h2>{chapter===1?"Five minutes of baseline control":info.incidentName}</h2><p>{chapter===1?"Save the preceding exercise to a downloaded JSON file, start a fresh baseline, advance five simulated minutes and pause.":"Introduce this predefined disturbance, advance ten simulated minutes and pause. The disturbance remains active until its expiry or an operator ends it."}</p><button className="walk-primary" disabled={pending||(chapter===2&&(!saved.baseline||!!saved.after))} onClick={chapter===1?prepare:incident}>{busy?"Preparing simulation…":chapter===1?"Save previous exercise & prepare baseline":saved.after?"Disturbance observation captured":"Run disturbance & capture response"}</button><small>{saved.baseline?`Baseline captured at T+${saved.baseline.minute} min` :"Capture a baseline to enable the disturbance."}{saved.after?` · response at T+${saved.after.minute} min`:""}</small><button onClick={()=>onOpen("training",domain)}>Open clocks, alarms & event log →</button></div><div className="walk-live"><span className="eyebrow">Current measurements · T+{plant?.elapsed_minutes??"—"} min</span>{info.tags.map((tag,i)=><div key={tag}><span>{info.labels[i]}</span><strong>{reading(plant,tag)} <small>{info.units[i]}</small></strong></div>)}<div><span>{plant?.operations?.impact?.label||"Service availability"}</span><strong>{plant?.operations?.impact?.coverage_pct?.toFixed(1)??"—"}<small>%</small></strong></div><p>{(plant?.active_alarms||plant?.alarms||[]).length} active alarms · {plant?.safety_state||"Waiting"}</p></div></section>}
    {chapter===3&&<section className="walk-agent-stage"><div className="walk-action"><span className="eyebrow">03 · Proposal → gate → evidence</span><h2>Ask the {HOSTED?"hosted":"local"} {info.name.toLowerCase()} agent</h2><p>Evaluate a captured copy of the current process. Show the audience the reason for acceptance or rejection before considering any actuation.</p><label><input type="checkbox" checked={thinking} onChange={e=>setThinking(e.target.checked)} /> Capture emitted reasoning (may take 1–2 minutes)</label><button className="walk-primary" disabled={pending||!ready||cooldown>0} title={cooldown>0?"The hosted lab allows one inference every ten seconds":undefined} onClick={()=>infer()}>{pending?(HOSTED?"Cloud agent working…":"Local agent working…"):cooldown>0?`Ready in ${cooldown}s…`:`Evaluate ${HOSTED?"cloud":"local"} agent · no actuation`}</button><button onClick={openEvidence}>Open the full decision inspector →</button><small>The walkthrough applies zero AI control changes. Live gated-auto experiments are available in the control rooms.</small></div><div className="walk-decision">{selected?<><span className={`walk-verdict ${selected.gate?.status}`}>{selected.gate?.status||selected.status} · no actuation</span><p>Recorded {new Date(selected.created_at).toLocaleString()} · {selected.domain} · T+{selected.before?.plant?.elapsed_minutes??"—"} min</p><h2>{selected.proposal?.objective||selected.proposal?.expected_effect||"Model response"}</h2><p>{selected.proposal?.explanation||selected.error}</p><dl>{Object.entries(selected.proposal?.changes||{}).filter(([,v])=>v!==null).map(([k,v])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{String(v)}</dd></div>)}</dl><p>{[...(selected.gate?.reasons||[]),...(selected.gate?.violated_constraints||[])].join(" · ")||"No gate constraint violations recorded."}</p><button onClick={()=>download(`decision-${selected.id}.json`,selected)}>Download this decision</button></>:<><span className="eyebrow">Evidence, not a verdict on alignment</span><h2>{pending?(HOSTED?"Inference is running in the cloud":"Inference is running locally"):"What will we inspect?"}</h2><ol><li>Exact observations and instructions</li><li>Proposed targets and stated rationale</li><li>Independent gate decision</li><li>Model provenance and optional reasoning text</li></ol>{validRecords.length>0&&<button onClick={()=>perform(async()=>setDecision(await api(`/agents/records/${validRecords[0].id}`)))}>Load latest saved decision</button>}<p>Saved evidence remains available if live inference is slow.</p></>}</div></section>}
    {chapter===4&&<section className="walk-evidence-stage"><div className="walk-comparison"><span className="eyebrow">Observed process response</span><h2>Baseline → disturbance</h2>{saved.baseline&&saved.after?<><table><thead><tr><th scope="col">Observation</th><th scope="col">T+{saved.baseline.minute} min</th><th scope="col">T+{saved.after.minute} min</th></tr></thead><tbody>{info.tags.map((tag,i)=><tr key={tag}><th scope="row">{info.labels[i]} ({info.units[i]})</th><td>{reading(saved.baseline,tag)}</td><td>{reading(saved.after,tag)}</td></tr>)}<tr><th scope="row">Active alarms</th><td>{saved.baseline.alarms.length}</td><td>{saved.after.alarms.length}</td></tr></tbody></table><button onClick={()=>download(`${domain}-demo-observations.json`,{domain,...saved,interpretation:"Baseline versus external disturbance; no AI actuation or causal optimization claim"})}>Export observations</button></>:<p>Capture the baseline and disturbance in chapters 2 and 3 to populate this comparison.</p>}<p>These observations show disturbance response. They do not measure an AI-caused improvement.</p></div><div className="walk-study"><span className="eyebrow">Controlled context probe</span><h2>Does an irrelevant label change the proposal?</h2><p>Two inferences. Identical process inputs. Only the socioeconomic label changes. Zero actuation.</p><button className="walk-primary" disabled={import.meta.env.VITE_HOSTED==='true'||pending||!ready} title={import.meta.env.VITE_HOSTED==='true'?'Run batch studies in the local lab':undefined} onClick={()=>infer(true)}>{pending?"Paired study running…":"Run paired label study"}</button>{latestStudy&&<div className="walk-study-result"><strong>{latestStudy.study.sample_size}/2 valid responses</strong><span>{latestStudy.study.sample_size<2?"Incomplete comparison":latestStudy.study.proposal_difference_observed?"Proposals differed in this pair":"Proposals matched in this pair"}</span><small>Recorded {new Date(latestStudy.created_at).toLocaleString()} · exploratory result</small></div>}<p>Small paired tests cannot prove alignment or absence of bias. Inspect individual records, then repeat across conditions.</p><button onClick={openEvidence}>Inspect study records →</button><button onClick={()=>onOpen("research",domain)}>Open the saved water & activation demo →</button></div></section>}
    <footer className="walk-footer"><span>Synthetic plants · illustrative dynamics · {HOSTED?"cloud inference":"local inference"}</span><div><button disabled={chapter===0} onClick={()=>setChapter(chapter-1)}>← Previous</button><button className="walk-primary" disabled={chapter===4} onClick={()=>setChapter(chapter+1)}>Next chapter →</button></div></footer>
  </main>;
}
