from __future__ import annotations

from datetime import datetime, timezone

import pytest

from shared.models import EquipmentState, PlantSnapshot, SensorValue


@pytest.fixture
def safe_snapshot() -> PlantSnapshot:
    values = {
        "raw_flow_m3h": (290.0, "m3/h"),
        "raw_turbidity_ntu": (8.0, "NTU"),
        "raw_ph": (7.35, "pH"),
        "raw_alkalinity_mg_l_caco3": (55.0, "mg/L as CaCO3"),
        "coagulation_ph": (6.78, "pH"),
        "settled_alkalinity_mg_l_caco3": (44.0, "mg/L as CaCO3"),
        "finished_water_ph": (7.30, "pH"),
        "finished_alkalinity_mg_l_caco3": (54.0, "mg/L as CaCO3"),
        "water_temperature_c": (15.0, "degC"),
        "clarified_turbidity_ntu": (1.2, "NTU"),
        "filtered_turbidity_ntu": (0.18, "NTU"),
        "filter_dp_kpa": (21.0, "kPa"),
        "clearwell_level_pct": (65.0, "%"),
        "clearwell_level_model_pct": (65.0, "%"),
        "clearwell_overflow_m3h": (0.0, "m3/h"),
        "chlorine_residual_mg_l": (1.15, "mg/L"),
        "chlorine_model_estimate_mg_l": (1.15, "mg/L"),
        "chlorine_dose_actual_mg_l": (1.45, "mg/L"),
        "chlorine_contact_time_min": (65.0, "min"),
        "chlorine_ct_mg_min_l": (74.8, "mg-min/L"),
        "hocl_fraction_pct": (61.3, "%"),
        "chlorine_feed_runtime_min": (60.0, "min"),
        "alum_feed_runtime_min": (60.0, "min"),
        "naoh_feed_runtime_min": (60.0, "min"),
        "coagulant_dose_actual_mg_l": (22.0, "mg/L"),
        "chemical_feed_flow_proof": (1.0, "bool"),
        "naoh_dose_actual_mg_l": (8.0, "mg/L"),
        "alum_day_tank_level_pct": (75.0, "%"),
        "naoh_day_tank_level_pct": (75.0, "%"),
        "hypochlorite_day_tank_level_pct": (75.0, "%"),
        "alum_solution_flow_lph": (8.13, "L/h"),
        "naoh_solution_flow_lph": (7.25, "L/h"),
        "hypochlorite_solution_flow_lph": (3.34, "L/h"),
        "distribution_flow_m3h": (228.0, "m3/h"),
        "elevated_tank_level_pct": (68.0, "%"),
        "zone_1_demand_m3h": (86.0, "m3/h"),
        "zone_2_demand_m3h": (78.0, "m3/h"),
        "zone_3_demand_m3h": (64.0, "m3/h"),
        "zone_1_pressure_m": (47.0, "m"),
        "zone_2_pressure_m": (44.0, "m"),
        "zone_3_pressure_m": (41.0, "m"),
        "leak_flow_m3h": (0.0, "m3/h"),
        "energy_kw": (52.0, "kW"),
        "intake_upstream_pressure_m": (6.0, "m"),
        "intake_downstream_pressure_m": (5.9, "m"),
        "filter_inlet_pressure_kpa": (116.0, "kPa"),
        "filter_outlet_pressure_kpa": (95.0, "kPa"),
        "pump_discharge_pressure_m": (58.0, "m"),
        "pump_deadhead_pressure_kpa": (0.0, "kPa"),
        "distribution_header_pressure_m": (52.0, "m"),
        "intake_gate_position_pct": (95.0, "%"),
        "filter_outlet_valve_position_pct": (95.0, "%"),
        "zone_1_isolation_valve_position_pct": (100.0, "%"),
        "zone_2_isolation_valve_position_pct": (100.0, "%"),
        "zone_3_isolation_valve_position_pct": (100.0, "%"),
        "zone_1_valve_dp_kpa": (1.0, "kPa"),
        "zone_2_valve_dp_kpa": (1.0, "kPa"),
        "zone_3_valve_dp_kpa": (1.0, "kPa"),
        "zone_1_served_m3h": (86.0, "m3/h"),
        "zone_2_served_m3h": (78.0, "m3/h"),
        "zone_3_served_m3h": (64.0, "m3/h"),
    }
    return PlantSnapshot(
        simulation_time=datetime(2026, 1, 1, tzinfo=timezone.utc),
        sensors={name: SensorValue(value=value, unit=unit) for name, (value, unit) in values.items()},
        equipment={"high_lift_pump": EquipmentState(running=True, speed_pct=70)},
        actuators={
            "intake_pump_speed_pct": 72.0,
            "high_lift_pump_speed_pct": 70.0,
            "booster_pump_speed_pct": 54.0,
            "outlet_valve_pct": 82.0,
            "intake_gate_pct": 95.0,
            "filter_outlet_valve_pct": 95.0,
            "zone_1_isolation_valve_pct": 100.0,
            "zone_2_isolation_valve_pct": 100.0,
            "zone_3_isolation_valve_pct": 100.0,
            "pressure_reducing_valve_setpoint_m": 52.0,
            "coagulant_dose_mg_l": 22.0,
            "chlorine_dose_mg_l": 1.45,
            "naoh_dose_mg_l": 8.0,
            "backwash_request": False,
            "emergency_stop": False,
        },
    )
