NAMESPACE_URI = "urn:waterlab:ot"

SENSOR_NODES = [
    "raw_flow_m3h", "raw_turbidity_ntu", "clarified_turbidity_ntu",
    "raw_ph", "raw_alkalinity_mg_l_caco3", "coagulation_ph",
    "settled_alkalinity_mg_l_caco3", "finished_water_ph",
    "finished_alkalinity_mg_l_caco3", "water_temperature_c",
    "filtered_turbidity_ntu", "filter_dp_kpa", "clearwell_level_pct",
    "clearwell_level_model_pct", "clearwell_overflow_m3h",
    "chlorine_residual_mg_l", "chlorine_model_estimate_mg_l", "chlorine_dose_actual_mg_l",
    "coagulant_dose_actual_mg_l", "chemical_feed_flow_proof",
    "distribution_flow_m3h",
    "chlorine_contact_time_min", "chlorine_ct_mg_min_l",
    "hocl_fraction_pct", "alum_feed_runtime_min", "chlorine_feed_runtime_min", "naoh_feed_runtime_min",
    "naoh_dose_actual_mg_l",
    "alum_solution_flow_lph", "naoh_solution_flow_lph", "hypochlorite_solution_flow_lph",
    "alum_bulk_tank_level_pct", "alum_day_tank_level_pct",
    "alum_transfer_valve_position_pct", "alum_injection_valve_position_pct",
    "naoh_bulk_tank_level_pct", "naoh_day_tank_level_pct",
    "naoh_transfer_valve_position_pct", "naoh_injection_valve_position_pct",
    "hypochlorite_bulk_tank_level_pct", "hypochlorite_day_tank_level_pct",
    "hypochlorite_transfer_valve_position_pct", "hypochlorite_injection_valve_position_pct",
    "elevated_tank_level_pct", "zone_1_demand_m3h", "zone_2_demand_m3h",
    "zone_3_demand_m3h", "zone_1_pressure_m", "zone_2_pressure_m",
    "zone_3_pressure_m", "leak_flow_m3h", "energy_kw",
    "intake_upstream_pressure_m", "intake_downstream_pressure_m",
    "filter_inlet_pressure_kpa", "filter_outlet_pressure_kpa",
    "pump_discharge_pressure_m", "pump_deadhead_pressure_kpa", "distribution_header_pressure_m",
    "intake_gate_position_pct", "filter_outlet_valve_position_pct",
    "zone_1_isolation_valve_position_pct", "zone_2_isolation_valve_position_pct",
    "zone_3_isolation_valve_position_pct", "zone_1_valve_dp_kpa",
    "zone_2_valve_dp_kpa", "zone_3_valve_dp_kpa",
    "zone_1_served_m3h", "zone_2_served_m3h", "zone_3_served_m3h",
]

ACTUATOR_NODES = [
    "intake_pump_speed_pct", "high_lift_pump_speed_pct",
    "booster_pump_speed_pct", "outlet_valve_pct",
    "intake_gate_pct", "filter_outlet_valve_pct",
    "zone_1_isolation_valve_pct", "zone_2_isolation_valve_pct",
    "zone_3_isolation_valve_pct", "pressure_reducing_valve_setpoint_m",
    "coagulant_dose_mg_l", "chlorine_dose_mg_l", "naoh_dose_mg_l",
    "backwash_request", "emergency_stop",
]
