import React,{useState,useRef} from 'react';
import InfrastructureScene from './InfrastructureScene';
import simulator from './assets/simulator.png';
export const DEMO='https://ot-aigent-simulation.night-zone.com';
const REPO='https://github.com/xienanzheng/ot-ai-assurance-lab';
const sectors={water:{name:'Water',concern:'Safe water. Continuous service.',detail:'Treatment, storage and distribution.'},nuclear:{name:'Nuclear',concern:'Protection retains priority.',detail:'Conceptual reactor and generation.'},grid:{name:'Power grid',concern:'Keep essential demand supplied.',detail:'Dispatch, storage and network balance.'}};
const work=[
 {title:'Keep intelligence local.',tag:'Deployment architecture',body:'Explore AI inside an isolated environment, using local models and plant context. Define what crosses the boundary, what stays inside, and how operators continue when AI is unavailable.',outcome:'Local inference · Information boundaries · Fallback design'},
 {title:'Put authority behind a gate.',tag:'Control assurance',body:'Evaluate each proposed action against process state, permitted controls and operating limits. Independent protection and deterministic control retain authority.',outcome:'Bounded actions · Process constraints · Human oversight'},
 {title:'Turn decisions into evidence.',tag:'Agent evaluation',body:'Inspect sensor context, proposals, gate decisions and measured outcomes. Preserve critical events and retrieve operator-reviewed lessons without letting the model rewrite its own permissions.',outcome:'Context memory · Reproducible trials · Decision records'},
 {title:'Build a shared practice.',tag:'Field building',body:'Connect technical researchers, infrastructure practitioners and policy communities around bounded AI-security questions. The Track II US–China work explores how dialogue can lead to comparable evidence and practical projects.',outcome:'Technical dialogue · Shared evaluations · Governance'}
];
function Arrow({diagonal=false}){return <svg className="arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d={diagonal?'M5 19L19 5M5 5h14v14':'M4 12h15M12 5l7 7-7 7'}/></svg>;}
function Mark(){return <svg viewBox="0 0 42 42" fill="none" aria-hidden="true"><path d="M16 6H6v30h10M26 6h10v30H26M15 21h12" stroke="currentColor" strokeWidth="4"/></svg>;}
function GateIllustration(){
 const [choice,setChoice]=useState('bounded');
 const safe=choice==='bounded';
 return <div className={`gate-interaction ${safe?'is-allowed':'is-blocked'}`}>
  <div className="gate-heading"><span>Try the boundary</span><span className="example-label">Illustrative example</span></div>
  <div className="gate-choices" aria-label="Choose an illustrative AI request">{[['bounded','Within authority'],['bypass','Bypass protection']].map(([id,label])=><button key={id} aria-pressed={choice===id} onClick={()=>setChoice(id)}>{label}</button>)}</div>
  <div className="gate-flow"><div><span>AI proposes</span><strong>{safe?'A bounded setpoint':'Disable a protection'}</strong></div><div className="boundary-symbol" aria-hidden="true"><Mark/></div><div><span>Independent gate</span><strong>{safe?'Evaluate constraints':'Reject request'}</strong></div></div>
  <p role="status">{safe?'Permission starts an evaluation. Current process conditions still decide whether a change is allowed.':'The request exceeds the agent’s authority. Protection remains independent of the model.'}</p>
 </div>;
}
export default function HomePage(){
 const [sector,setSector]=useState('water'),[menu,setMenu]=useState(false),[expanded,setExpanded]=useState(0);
 const scene=useRef(null);
 function move(e){if(!matchMedia('(hover: hover) and (prefers-reduced-motion: no-preference)').matches)return;const r=e.currentTarget.getBoundingClientRect();scene.current?.style.setProperty('--scene-x',`${(e.clientX-r.left-r.width/2)*.018}px`);scene.current?.style.setProperty('--scene-y',`${(e.clientY-r.top-r.height/2)*.018}px`);}
 const close=()=>setMenu(false);
 return <>
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="site-header"><a className="brand" href="#" aria-label="Secure Critical Infrastructure home"><Mark/><span>Secure Critical<br/>Infrastructure<span className="brand-stop">.</span></span></a><button className="menu-toggle" aria-expanded={menu} aria-controls="site-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}<span aria-hidden="true">{menu?'−':'+'}</span></button><nav id="site-nav" className={menu?'is-open':''} aria-label="Main navigation"><a href="#mission" onClick={close}>Mission</a><a href="#approach" onClick={close}>Our approach</a><a href="#about" onClick={close}>About</a><a className="nav-demo" href={DEMO}>See demo <Arrow diagonal/></a></nav></header>
  <main id="main">
   <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><div className="hero-intro"><span className="signal-dot"/>Cybersecurity × AI assurance</div><h1 id="hero-title">Critical systems.<br/><span>Human control.</span></h1><p>Bring AI into the systems we depend on.<br className="desktop-break"/> Keep the authority to decide.</p><div className="hero-actions"><a className="button primary" href={DEMO}>See the demo <Arrow diagonal/></a><a className="text-link" href="#mission">Meet the mission <Arrow/></a></div><div className="hero-footnote"><span className="small-cross" aria-hidden="true">+</span><span>Research-led. Grounded in operations.</span></div></div><div className="hero-visual" onPointerMove={move} onPointerLeave={()=>{scene.current?.style.setProperty('--scene-x','0px');scene.current?.style.setProperty('--scene-y','0px');}}><div className="scene-caption"><span>Systems worth protecting</span><span aria-hidden="true">↗</span></div><div ref={scene} className="scene"><InfrastructureScene sector={sector}/></div><div className="scene-status" aria-live="polite"><span className="status-bracket" aria-hidden="true">↳</span><div><strong>{sectors[sector].concern}</strong><span>{sectors[sector].detail}</span></div><span className="scene-status-icon" aria-hidden="true">✳</span></div></div></section>
   <div className="sector-strip"><span>Explore the systems</span><div>{Object.entries(sectors).map(([key,s])=><button key={key} aria-pressed={sector===key} onClick={()=>setSector(key)} onMouseEnter={()=>setSector(key)}><span>{s.name}</span><Arrow diagonal/></button>)}</div><span className="strip-note">Select a sector ↗</span></div>
   <section id="mission" className="mission"><div className="mission-label">The mission</div><div className="mission-content"><h2>Intelligence belongs<br/>where it can be<br/><span>held accountable.</span></h2><div className="mission-bottom"><p>Critical infrastructure keeps everyday life moving. AI should help operators understand their systems, make better decisions and stay in control when conditions change.</p><p>Our work asks a practical question: how can infrastructure benefit from AI while preserving isolation, independent protection and human authority?</p></div></div><span className="mission-mark" aria-hidden="true"><Mark/></span></section>
   <section id="approach" className="approach section-wrap"><div className="section-lead"><h2>Closer to the process.<br/>Clearer on the risk.</h2><p>Cyber and AI assurance, built around the decisions that matter in operations.</p></div><div className="approach-layout"><div className="work-list">{work.map((item,i)=><div className={`work-item ${expanded===i?'expanded':''}`} key={item.title}><h3><button id={`work-button-${i}`} aria-expanded={expanded===i} aria-controls={`work-panel-${i}`} onClick={()=>setExpanded(expanded===i?-1:i)}><span>{item.title}<small>{item.tag}</small></span><span className="expand-sign" aria-hidden="true">{expanded===i?'−':'+'}</span></button></h3><div id={`work-panel-${i}`} role="region" aria-labelledby={`work-button-${i}`} hidden={expanded!==i}><p>{item.body}</p><span className="work-outcome">{item.outcome}</span></div></div>)}</div><div className="approach-aside"><GateIllustration/><p className="aside-note">Identity tells us who can act. Process context helps determine whether the action is safe.</p></div></div></section>
   <section id="lab" className="lab-section"><div className="lab-copy"><span className="lab-label"><span className="signal-dot"/>Open research lab</span><h2>Step into the<br/>control room.</h2><p>Change a scenario. Watch the sensors. Inspect what the AI proposes and what the gate allows.</p><a className="button light" href={DEMO}>Launch the simulator <Arrow diagonal/></a><div className="lab-limits"><span>Water / Nuclear / Power grid</span><span>20 minutes · 10 AI calls per session</span></div></div><a className="lab-preview" href={DEMO} aria-label="Open the live OT AI assurance simulator"><div className="preview-bar"><span><i/><i/><i/></span><span>OT / AI assurance lab</span><Arrow diagonal/></div><div className="preview-image"><img src={simulator} width="1440" height="2215" alt="Actual power-grid simulator with generation, demand, sensor readings and a five-bus network" loading="lazy"/></div><div className="preview-caption"><span>Actual simulator interface</span><span>Enter the lab <Arrow/></span></div></a></section>
   <div className="evidence-strip"><p><strong>A working prototype. An open question.</strong> The lab tests control boundaries. It does not establish safe deployment in a real plant. The online demo uses cloud AI; the local lab supports offline inference after setup.</p><a className="text-link" href={`${DEMO}/research.html`}>Explore the findings <Arrow diagonal/></a></div>
   <section id="about" className="about section-wrap"><div className="about-title"><span className="about-emblem" aria-hidden="true"><Mark/></span><h2>From infrastructure.<br/>For its future.</h2></div><div className="about-copy"><h3>Isaac (Nanzheng)</h3><p className="about-role">Cybersecurity practitioner · M3 fellow</p><p>My work began in cybersecurity for Singapore’s water infrastructure at PUB. That experience shapes the question behind this project: what does it take to give AI useful responsibility in systems people rely on?</p><p>Through the M3 fellowship, I’m developing an open simulation lab and exploring Track II US–China dialogue on AI security, with Singapore as a potential convening point.</p><p>The aim is to bring operational experience, technical evidence and governance into the same conversation.</p><a className="text-link" href="https://github.com/xienanzheng">Connect with Isaac on GitHub <Arrow diagonal/></a></div></section>
   <section className="closing"><div><span>For operators. For researchers. For the public good.</span><h2>Make the boundary<br/>worth trusting.</h2></div><a className="closing-cta" href={DEMO}><span>See demo</span><Arrow diagonal/></a></section>
  </main>
  <footer><a className="brand footer-brand" href="#"><Mark/><span>Secure Critical<br/>Infrastructure.</span></a><div><a href={REPO}>Open source <Arrow diagonal/></a><a href={`${REPO}/blob/main/docs/VERIFICATION_2026_09_18.md`}>Test evidence <Arrow diagonal/></a><a href="#about">About the work <Arrow/></a></div><p>© {new Date().getFullYear()} Secure Critical Infrastructure<br/><span>An independent research initiative.</span></p></footer>
 </>;
}
